### ISSUE TITLE
Your .env file is checked into source

### ISSUE THREAD

**Issue by devonestes** [mameneses/happy_tree#1]
Hey dude,

Fellow DBC grad here. Just wanted to let you know that your `.env` file with what looks to be some sensitive information is checked into this repo. You might want to add that to your `.gitignore` and also go through and remove it from all your previous commits so you don't have folks running off with your info!

**Comment by mameneses** [comment]
Hi man,

Thanks for the heads up! I remember when i made that rookie mistake. I fixed it in deployment when I created two new repos to separate my client and server for easier updating and deployment workflow. In my new happytree_server repo (https://github.com/mameneses/happytree_server) i created a new Mongolab DB and correctly put the sensitive information in the .gitignore file. Luckily that old DB does not have anything but test and dummy data, but you are right, i should go back and clean it up so i don't look like such a rookie :).
